"""Seeded Singapore job listings.

MyCareersFuture (Singapore's national job portal) does not expose a public
job-search API, so this module stands in for that data source using the same
adapter pattern as `app.seed_data.skillsfuture_courses`. To plug in a real
integration later, implement a fetcher with the same list-of-dict shape as
`load_seeded_jobs()` and swap the call in `app.providers.job_provider`.
"""

SEEDED_JOBS = [
    {
        "external_id": "job-001",
        "title": "Data Analyst",
        "company": "DBS Bank",
        "category": "Data & Analytics",
        "description": "Analyze customer transaction data to identify trends and support product decisions. Build dashboards in Tableau/Power BI and write SQL queries against large datasets.",
        "salary_min_sgd": 4000,
        "salary_max_sgd": 5500,
        "skills_required": ["SQL", "Data Analysis", "Tableau", "Power BI", "Excel"],
        "url": "https://www.mycareersfuture.gov.sg/job/data-analyst-dbs",
    },
    {
        "external_id": "job-002",
        "title": "Junior Data Scientist",
        "company": "Grab",
        "category": "Data & Analytics",
        "description": "Support the ML platform team building demand-forecasting models. Work with Python, scikit-learn, and large-scale data pipelines.",
        "salary_min_sgd": 5000,
        "salary_max_sgd": 7000,
        "skills_required": ["Python", "Machine Learning", "scikit-learn", "SQL", "Statistics"],
        "url": "https://www.mycareersfuture.gov.sg/job/junior-data-scientist-grab",
    },
    {
        "external_id": "job-003",
        "title": "Business Intelligence Executive",
        "company": "Singtel",
        "category": "Data & Analytics",
        "description": "Own the reporting stack for the consumer business unit, building Power BI dashboards and automating data refreshes.",
        "salary_min_sgd": 3800,
        "salary_max_sgd": 5000,
        "skills_required": ["Power BI", "Data Analysis", "SQL", "Dashboards"],
        "url": "https://www.mycareersfuture.gov.sg/job/bi-executive-singtel",
    },
    {
        "external_id": "job-004",
        "title": "Cloud Support Engineer",
        "company": "AWS Singapore",
        "category": "Technology",
        "description": "Provide technical support for enterprise customers running workloads on AWS. Troubleshoot EC2, S3, and IAM issues.",
        "salary_min_sgd": 4500,
        "salary_max_sgd": 6500,
        "skills_required": ["AWS", "Cloud Computing", "EC2", "IAM", "Networking"],
        "url": "https://www.mycareersfuture.gov.sg/job/cloud-support-engineer-aws",
    },
    {
        "external_id": "job-005",
        "title": "Cybersecurity Analyst",
        "company": "GovTech",
        "category": "Technology",
        "description": "Monitor security alerts, investigate incidents, and support risk assessments for government digital services.",
        "salary_min_sgd": 4200,
        "salary_max_sgd": 6000,
        "skills_required": ["Cybersecurity", "Network Security", "Risk Management", "Incident Response"],
        "url": "https://www.mycareersfuture.gov.sg/job/cybersecurity-analyst-govtech",
    },
    {
        "external_id": "job-006",
        "title": "Frontend Developer",
        "company": "Shopee",
        "category": "Technology",
        "description": "Build customer-facing features using React and TypeScript. Collaborate with design and backend teams in an agile squad.",
        "salary_min_sgd": 4800,
        "salary_max_sgd": 7200,
        "skills_required": ["JavaScript", "React", "HTML", "CSS", "TypeScript"],
        "url": "https://www.mycareersfuture.gov.sg/job/frontend-developer-shopee",
    },
    {
        "external_id": "job-007",
        "title": "IT Support Specialist (Career Switch)",
        "company": "NCS Group",
        "category": "Technology",
        "description": "Entry-level role providing helpdesk and basic infrastructure support. Great for career switchers with foundational Python or scripting skills.",
        "salary_min_sgd": 2800,
        "salary_max_sgd": 3600,
        "skills_required": ["Programming Fundamentals", "Python", "Networking"],
        "url": "https://www.mycareersfuture.gov.sg/job/it-support-ncs",
    },
    {
        "external_id": "job-008",
        "title": "Digital Marketing Executive",
        "company": "Lazada",
        "category": "Marketing",
        "description": "Run paid social and search campaigns, track performance via Google Analytics, and optimize conversion funnels.",
        "salary_min_sgd": 3500,
        "salary_max_sgd": 4800,
        "skills_required": ["SEO", "SEM", "Social Media Marketing", "Google Analytics"],
        "url": "https://www.mycareersfuture.gov.sg/job/digital-marketing-lazada",
    },
    {
        "external_id": "job-009",
        "title": "Content Marketing Specialist",
        "company": "PropertyGuru",
        "category": "Marketing",
        "description": "Own the content calendar across blog, email, and social. Write copy that drives lead generation.",
        "salary_min_sgd": 3600,
        "salary_max_sgd": 4900,
        "skills_required": ["Copywriting", "Content Marketing", "Branding"],
        "url": "https://www.mycareersfuture.gov.sg/job/content-marketing-propertyguru",
    },
    {
        "external_id": "job-010",
        "title": "UX/UI Designer",
        "company": "Carousell",
        "category": "Design",
        "description": "Design end-to-end user flows for a marketplace app used by millions. Conduct user research and prototype in Figma.",
        "salary_min_sgd": 4200,
        "salary_max_sgd": 6200,
        "skills_required": ["UX Design", "UI Design", "Figma", "Prototyping"],
        "url": "https://www.mycareersfuture.gov.sg/job/ux-ui-designer-carousell",
    },
    {
        "external_id": "job-011",
        "title": "Graphic Designer",
        "company": "Mediacorp",
        "category": "Design",
        "description": "Create visual assets for broadcast and digital campaigns using Photoshop and Illustrator.",
        "salary_min_sgd": 3200,
        "salary_max_sgd": 4300,
        "skills_required": ["Photoshop", "Illustrator", "Graphic Design"],
        "url": "https://www.mycareersfuture.gov.sg/job/graphic-designer-mediacorp",
    },
    {
        "external_id": "job-012",
        "title": "Project Coordinator",
        "company": "Keppel Corporation",
        "category": "Business",
        "description": "Support project managers with scheduling, documentation, and stakeholder coordination on infrastructure projects.",
        "salary_min_sgd": 3400,
        "salary_max_sgd": 4500,
        "skills_required": ["Project Management", "Agile", "Communication"],
        "url": "https://www.mycareersfuture.gov.sg/job/project-coordinator-keppel",
    },
    {
        "external_id": "job-013",
        "title": "Scrum Master",
        "company": "OCBC Bank",
        "category": "Business",
        "description": "Facilitate Scrum ceremonies for a digital banking squad, remove blockers, and coach teams on Agile best practices.",
        "salary_min_sgd": 5500,
        "salary_max_sgd": 7500,
        "skills_required": ["Agile", "Scrum", "Project Management"],
        "url": "https://www.mycareersfuture.gov.sg/job/scrum-master-ocbc",
    },
    {
        "external_id": "job-014",
        "title": "Financial Analyst",
        "company": "Temasek",
        "category": "Finance",
        "description": "Build financial models and valuation analyses to support investment decisions across portfolio companies.",
        "salary_min_sgd": 5000,
        "salary_max_sgd": 7000,
        "skills_required": ["Financial Modelling", "Excel", "Valuation"],
        "url": "https://www.mycareersfuture.gov.sg/job/financial-analyst-temasek",
    },
    {
        "external_id": "job-015",
        "title": "FinTech Product Associate",
        "company": "StashAway",
        "category": "Finance",
        "description": "Support product development for a robo-advisory platform, working closely with engineering and compliance teams.",
        "salary_min_sgd": 4200,
        "salary_max_sgd": 5800,
        "skills_required": ["FinTech", "Blockchain", "Digital Payments"],
        "url": "https://www.mycareersfuture.gov.sg/job/fintech-product-stashaway",
    },
    {
        "external_id": "job-016",
        "title": "HR Executive",
        "company": "Singapore Airlines",
        "category": "Business",
        "description": "Support end-to-end recruitment and onboarding for cabin crew and ground staff roles.",
        "salary_min_sgd": 3200,
        "salary_max_sgd": 4200,
        "skills_required": ["Human Resources", "Recruitment", "Performance Management"],
        "url": "https://www.mycareersfuture.gov.sg/job/hr-executive-sia",
    },
    {
        "external_id": "job-017",
        "title": "Supply Chain Executive",
        "company": "Flex",
        "category": "Business",
        "description": "Coordinate procurement and inventory planning across regional manufacturing sites.",
        "salary_min_sgd": 3600,
        "salary_max_sgd": 4800,
        "skills_required": ["Supply Chain", "Logistics", "Inventory Management"],
        "url": "https://www.mycareersfuture.gov.sg/job/supply-chain-flex",
    },
    {
        "external_id": "job-018",
        "title": "Healthcare Support Officer",
        "company": "Singapore General Hospital",
        "category": "Healthcare",
        "description": "Assist nursing staff with patient care duties and ward operations. On-the-job training provided.",
        "salary_min_sgd": 2600,
        "salary_max_sgd": 3200,
        "skills_required": ["Patient Care", "Healthcare", "Communication"],
        "url": "https://www.mycareersfuture.gov.sg/job/healthcare-support-sgh",
    },
    {
        "external_id": "job-019",
        "title": "Team Lead, Operations",
        "company": "Sea Group",
        "category": "Leadership",
        "description": "Lead a team of 8 operations executives, coach performance, and drive process improvements.",
        "salary_min_sgd": 5200,
        "salary_max_sgd": 7000,
        "skills_required": ["Leadership", "People Management", "Coaching"],
        "url": "https://www.mycareersfuture.gov.sg/job/team-lead-operations-sea",
    },
    {
        "external_id": "job-020",
        "title": "Data Engineer",
        "company": "Razer",
        "category": "Data & Analytics",
        "description": "Build and maintain ETL pipelines feeding the analytics warehouse. Work with SQL, Python, and orchestration tools.",
        "salary_min_sgd": 5000,
        "salary_max_sgd": 7500,
        "skills_required": ["Data Engineering", "ETL", "SQL", "Data Warehousing", "Python"],
        "url": "https://www.mycareersfuture.gov.sg/job/data-engineer-razer",
    },
]


def load_seeded_jobs() -> list[dict]:
    return SEEDED_JOBS
