"""Seeded SkillsFuture-style course dataset.

There is no official public API for the MySkillsFuture course directory, so
this module stands in for that data source. It implements the same shape
`app.providers.skillsfuture_provider.SkillsFutureProvider` expects, so
swapping this out for a real integration later (an authorized data feed, or
a scraper of the public course directory at
https://www.myskillsfuture.gov.sg/content/portal/en/training-exchange/course-directory.html)
only requires replacing `load_seeded_courses()` - nothing downstream changes.

Course fees and credit amounts are illustrative, modeled on real SkillsFuture
listings circa 2025-2026, not scraped from a live source.
"""

SEEDED_SKILLSFUTURE_COURSES = [
    {
        "external_id": "sf-001",
        "title": "Data Analytics with Python for Business",
        "provider": "NTUC LearningHub",
        "category": "Data & Analytics",
        "description": "Hands-on introduction to Python, Pandas, and data visualization for business decision-making. Covers data cleaning, exploratory analysis, and dashboard building.",
        "duration_hours": 40,
        "price_sgd": 1800,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Python", "Pandas", "Data Analysis", "Data Visualization", "Excel"],
        "url": "https://www.ntuclearninghub.com/courses/data-analytics-python",
    },
    {
        "external_id": "sf-002",
        "title": "SQL for Data Analysis",
        "provider": "General Assembly",
        "category": "Data & Analytics",
        "description": "Learn to query, join, and aggregate relational databases using SQL. Includes real-world case studies with PostgreSQL.",
        "duration_hours": 24,
        "price_sgd": 950,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["SQL", "PostgreSQL", "Data Analysis"],
        "url": "https://generalassemb.ly/education/sql-for-data-analysis/singapore",
    },
    {
        "external_id": "sf-003",
        "title": "Tableau for Data Visualization",
        "provider": "Vertical Institute",
        "category": "Data & Analytics",
        "description": "Build interactive dashboards and visual reports in Tableau, from data connection to publishing on Tableau Server.",
        "duration_hours": 20,
        "price_sgd": 1200,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Tableau", "Data Visualization", "Dashboards"],
        "url": "https://verticalinstitute.com/courses/tableau",
    },
    {
        "external_id": "sf-004",
        "title": "Foundations of Machine Learning",
        "provider": "SMU Academy",
        "category": "Data & Analytics",
        "description": "Introduces supervised and unsupervised learning, model evaluation, and practical ML workflows using scikit-learn.",
        "duration_hours": 48,
        "price_sgd": 2600,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Machine Learning", "Python", "scikit-learn", "Statistics"],
        "url": "https://academy.smu.edu.sg/courses/foundations-machine-learning",
    },
    {
        "external_id": "sf-005",
        "title": "Cloud Computing Essentials (AWS)",
        "provider": "NTUC LearningHub",
        "category": "Technology",
        "description": "Covers core AWS services - EC2, S3, IAM, VPC - and prepares learners for the AWS Cloud Practitioner certification.",
        "duration_hours": 32,
        "price_sgd": 1500,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["AWS", "Cloud Computing", "IAM", "EC2"],
        "url": "https://www.ntuclearninghub.com/courses/aws-cloud-essentials",
    },
    {
        "external_id": "sf-006",
        "title": "Cybersecurity Fundamentals",
        "provider": "Republic Polytechnic CET",
        "category": "Technology",
        "description": "Introduces network security, threat modeling, and incident response fundamentals for IT professionals.",
        "duration_hours": 36,
        "price_sgd": 1650,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Cybersecurity", "Network Security", "Risk Management"],
        "url": "https://www.rp.edu.sg/cet/cybersecurity-fundamentals",
    },
    {
        "external_id": "sf-007",
        "title": "Full-Stack Web Development Bootcamp",
        "provider": "General Assembly",
        "category": "Technology",
        "description": "Intensive bootcamp covering HTML, CSS, JavaScript, React, and Node.js to build and deploy full-stack web applications.",
        "duration_hours": 480,
        "price_sgd": 14900,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["JavaScript", "React", "Node.js", "HTML", "CSS"],
        "url": "https://generalassemb.ly/education/software-engineering-immersive/singapore",
    },
    {
        "external_id": "sf-008",
        "title": "Python Programming for Beginners",
        "provider": "Nanyang Polytechnic CET Academy",
        "category": "Technology",
        "description": "Beginner-friendly introduction to Python syntax, control flow, functions, and basic scripting for automation.",
        "duration_hours": 24,
        "price_sgd": 850,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Python", "Programming Fundamentals"],
        "url": "https://www.nyp.edu.sg/cet/courses/python-programming-beginners",
    },
    {
        "external_id": "sf-009",
        "title": "Digital Marketing Strategy",
        "provider": "Marketing Institute of Singapore",
        "category": "Marketing",
        "description": "Covers SEO, SEM, social media advertising, and campaign analytics to build a digital marketing strategy from scratch.",
        "duration_hours": 30,
        "price_sgd": 1400,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["SEO", "SEM", "Social Media Marketing", "Google Analytics"],
        "url": "https://mis.edu.sg/courses/digital-marketing-strategy",
    },
    {
        "external_id": "sf-010",
        "title": "Content Marketing & Copywriting",
        "provider": "General Assembly",
        "category": "Marketing",
        "description": "Practical workshop on writing for brands, content calendars, and measuring content ROI across channels.",
        "duration_hours": 16,
        "price_sgd": 780,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Copywriting", "Content Marketing", "Branding"],
        "url": "https://generalassemb.ly/education/content-marketing/singapore",
    },
    {
        "external_id": "sf-011",
        "title": "UX/UI Design Fundamentals",
        "provider": "Vertical Institute",
        "category": "Design",
        "description": "Learn user research, wireframing, prototyping in Figma, and usability testing to design digital products.",
        "duration_hours": 36,
        "price_sgd": 1900,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["UX Design", "UI Design", "Figma", "Prototyping"],
        "url": "https://verticalinstitute.com/courses/ux-ui-design",
    },
    {
        "external_id": "sf-012",
        "title": "Graphic Design with Adobe Creative Suite",
        "provider": "Temasek Polytechnic CET",
        "category": "Design",
        "description": "Hands-on training in Photoshop, Illustrator, and InDesign for print and digital design projects.",
        "duration_hours": 40,
        "price_sgd": 1350,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Photoshop", "Illustrator", "Graphic Design"],
        "url": "https://www.tp.edu.sg/cet/adobe-creative-suite",
    },
    {
        "external_id": "sf-013",
        "title": "Project Management Professional (PMP) Prep",
        "provider": "Institute of Systems Science, NUS",
        "category": "Business",
        "description": "Comprehensive preparation for the PMP certification exam, covering scope, schedule, cost, and risk management.",
        "duration_hours": 35,
        "price_sgd": 2200,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Project Management", "PMP", "Risk Management", "Agile"],
        "url": "https://iss.nus.edu.sg/courses/pmp-preparation",
    },
    {
        "external_id": "sf-014",
        "title": "Agile & Scrum Foundations",
        "provider": "NTUC LearningHub",
        "category": "Business",
        "description": "Introduces Agile principles, Scrum roles and ceremonies, and how to run effective sprints.",
        "duration_hours": 16,
        "price_sgd": 900,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Agile", "Scrum", "Project Management"],
        "url": "https://www.ntuclearninghub.com/courses/agile-scrum-foundations",
    },
    {
        "external_id": "sf-015",
        "title": "Financial Modelling & Analysis",
        "provider": "Institute of Banking & Finance",
        "category": "Finance",
        "description": "Build financial models in Excel, covering valuation, forecasting, and scenario analysis for business decisions.",
        "duration_hours": 28,
        "price_sgd": 1750,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Financial Modelling", "Excel", "Valuation"],
        "url": "https://www.ibf.org.sg/courses/financial-modelling-analysis",
    },
    {
        "external_id": "sf-016",
        "title": "Introduction to FinTech",
        "provider": "SMU Academy",
        "category": "Finance",
        "description": "Overview of blockchain, digital payments, robo-advisory, and regulatory trends shaping Singapore's FinTech sector.",
        "duration_hours": 20,
        "price_sgd": 1300,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["FinTech", "Blockchain", "Digital Payments"],
        "url": "https://academy.smu.edu.sg/courses/introduction-fintech",
    },
    {
        "external_id": "sf-017",
        "title": "Human Resource Management Essentials",
        "provider": "Singapore Human Resources Institute",
        "category": "Business",
        "description": "Covers recruitment, performance management, employment law, and HR analytics fundamentals.",
        "duration_hours": 24,
        "price_sgd": 1100,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Human Resources", "Recruitment", "Performance Management"],
        "url": "https://www.shri.org.sg/courses/hr-management-essentials",
    },
    {
        "external_id": "sf-018",
        "title": "Business Analytics with Power BI",
        "provider": "NTUC LearningHub",
        "category": "Data & Analytics",
        "description": "Learn to build interactive reports and dashboards in Power BI, from data modelling to DAX formulas.",
        "duration_hours": 24,
        "price_sgd": 1250,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Power BI", "Data Analysis", "DAX", "Dashboards"],
        "url": "https://www.ntuclearninghub.com/courses/power-bi-business-analytics",
    },
    {
        "external_id": "sf-019",
        "title": "Generative AI for the Workplace",
        "provider": "Vertical Institute",
        "category": "Technology",
        "description": "Practical guide to using large language models and generative AI tools to automate workplace tasks.",
        "duration_hours": 12,
        "price_sgd": 680,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Generative AI", "Prompt Engineering", "Automation"],
        "url": "https://verticalinstitute.com/courses/generative-ai-workplace",
    },
    {
        "external_id": "sf-020",
        "title": "Mandarin for Business Communication",
        "provider": "Nanyang Polytechnic CET Academy",
        "category": "Languages",
        "description": "Conversational and written Mandarin tailored for client meetings, negotiations, and business correspondence.",
        "duration_hours": 30,
        "price_sgd": 750,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Mandarin", "Business Communication"],
        "url": "https://www.nyp.edu.sg/cet/courses/mandarin-business",
    },
    {
        "external_id": "sf-021",
        "title": "Supply Chain & Logistics Management",
        "provider": "Republic Polytechnic CET",
        "category": "Business",
        "description": "Covers procurement, inventory management, and logistics optimization for manufacturing and retail sectors.",
        "duration_hours": 32,
        "price_sgd": 1450,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Supply Chain", "Logistics", "Inventory Management"],
        "url": "https://www.rp.edu.sg/cet/supply-chain-logistics",
    },
    {
        "external_id": "sf-022",
        "title": "Healthcare Support Skills Certificate",
        "provider": "Institute of Technical Education",
        "category": "Healthcare",
        "description": "Foundational training for healthcare support roles, covering patient care basics, hygiene protocols, and communication.",
        "duration_hours": 60,
        "price_sgd": 980,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Patient Care", "Healthcare", "Communication"],
        "url": "https://www.ite.edu.sg/cet/healthcare-support-skills",
    },
    {
        "external_id": "sf-023",
        "title": "Culinary Arts for Career Switchers",
        "provider": "At-Sunrice GlobalChef Academy",
        "category": "Hospitality",
        "description": "Introductory professional culinary training covering knife skills, kitchen safety, and menu fundamentals.",
        "duration_hours": 120,
        "price_sgd": 3200,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Culinary Arts", "Kitchen Safety", "Food Preparation"],
        "url": "https://www.at-sunrice.com/courses/culinary-career-switchers",
    },
    {
        "external_id": "sf-024",
        "title": "Effective Leadership & People Management",
        "provider": "SMU Academy",
        "category": "Leadership",
        "description": "Develops core leadership skills - coaching, feedback, delegation, and managing team performance.",
        "duration_hours": 16,
        "price_sgd": 1100,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Leadership", "People Management", "Coaching"],
        "url": "https://academy.smu.edu.sg/courses/effective-leadership",
    },
    {
        "external_id": "sf-025",
        "title": "Data Engineering Fundamentals",
        "provider": "General Assembly",
        "category": "Data & Analytics",
        "description": "Introduces ETL pipelines, data warehousing concepts, and orchestration tools for aspiring data engineers.",
        "duration_hours": 40,
        "price_sgd": 2100,
        "skillsfuture_credit_eligible": True,
        "skillsfuture_credit_amount": 500,
        "skills": ["Data Engineering", "ETL", "SQL", "Data Warehousing"],
        "url": "https://generalassemb.ly/education/data-engineering/singapore",
    },
]


def load_seeded_courses() -> list[dict]:
    return SEEDED_SKILLSFUTURE_COURSES
